//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VisualTrace {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VisualTrace.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 关于.
        /// </summary>
        internal static string ABOUT {
            get {
                return ResourceManager.GetString("ABOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VisualTrace.
        /// </summary>
        internal static string APPTITLE {
            get {
                return ResourceManager.GetString("APPTITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to traceroute 需要接收特殊的 ICMP 响应报文来构建完整的 traceroute 信息；但默认情况下，Windows 防火墙会拦截此类消息，导致您只能看到 traceroute 的最后一跳。
        ///
        ///您可以点击“是”来自动添加防火墙规则，也可以点“否”取消这一操作。.
        /// </summary>
        internal static string ASK_ADD_ICMP_FIREWALL_RULE {
            get {
                return ResourceManager.GetString("ASK_ADD_ICMP_FIREWALL_RULE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 平均延迟.
        /// </summary>
        internal static string AVRG {
            get {
                return ResourceManager.GetString("AVRG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to window.traceroute = {
        ///	Hops: [],
        ///	reset: function (hideMapPopup = false) {
        ///		map.enableScrollWheelZoom(true); //滚轮
        ///		map.clearOverlays(); //清除覆盖物
        ///		this.Hops = [];
        ///		this.hideMapPopup = hideMapPopup;
        ///		if (document.getElementById(&quot;traceroutePopup&quot;)) document.getElementById(&quot;traceroutePopup&quot;).remove();
        ///	},
        ///
        ///	addHop: function (hop) {
        ///		hop = JSON.parse(hop);
        ///		console.log(hop);
        ///		this.Hops.push(hop);
        ///		// 重新计算中心点并画图
        ///		map.clearOverlays(); //清除覆盖物
        ///		var pointlygon_array = []; //折线需要的数组
        ///		for (var i = 0; i &lt; th [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string baiduMap {
            get {
                return ResourceManager.GetString("baiduMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 最小延迟.
        /// </summary>
        internal static string BEST {
            get {
                return ResourceManager.GetString("BEST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 取消.
        /// </summary>
        internal static string CANCEL {
            get {
                return ResourceManager.GetString("CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 关闭.
        /// </summary>
        internal static string CLOSE {
            get {
                return ResourceManager.GetString("CLOSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 把地理位置和组织信息合为一栏.
        /// </summary>
        internal static string COMBINE_GEO_ORG {
            get {
                return ResourceManager.GetString("COMBINE_GEO_ORG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 复制.
        /// </summary>
        internal static string COPY {
            get {
                return ResourceManager.GetString("COPY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 自定义DNS服务器（仅支持UDP）.
        /// </summary>
        internal static string CUSTOM_DNS_RESOLVERS {
            get {
                return ResourceManager.GetString("CUSTOM_DNS_RESOLVERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 延迟提示时间(ms).
        /// </summary>
        internal static string DELAY_TIME {
            get {
                return ResourceManager.GetString("DELAY_TIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 禁用地理位置.
        /// </summary>
        internal static string DISABLE_IPGEO {
            get {
                return ResourceManager.GetString("DISABLE_IPGEO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 目标端口 / 初始序号.
        /// </summary>
        internal static string DST_PORT_INIT_SEQ {
            get {
                return ResourceManager.GetString("DST_PORT_INIT_SEQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP 或 域名不能为空.
        /// </summary>
        internal static string EMPTY_HOSTNAME_MSGBOX {
            get {
                return ResourceManager.GetString("EMPTY_HOSTNAME_MSGBOX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Traceroute 产生了一个或多个异常输出，请检查下面的输出信息以排查问题。.
        /// </summary>
        internal static string EXC_OUTPUT_FORM_PROMPT {
            get {
                return ResourceManager.GetString("EXC_OUTPUT_FORM_PROMPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 异常输出.
        /// </summary>
        internal static string EXC_OUTPUT_FORM_TITLE {
            get {
                return ResourceManager.GetString("EXC_OUTPUT_FORM_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to traceroute进程异常退出，请参考错误消息以了解更多信息。退出代码：.
        /// </summary>
        internal static string EXCEPTIONAL_EXIT_MSG {
            get {
                return ResourceManager.GetString("EXCEPTIONAL_EXIT_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 添加防火墙规则失败.
        /// </summary>
        internal static string FAILED_TO_ADD_RULES {
            get {
                return ResourceManager.GetString("FAILED_TO_ADD_RULES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 首个跃点.
        /// </summary>
        internal static string FIRST_TTL_HOP {
            get {
                return ResourceManager.GetString("FIRST_TTL_HOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 常规设置.
        /// </summary>
        internal static string GENERAL {
            get {
                return ResourceManager.GetString("GENERAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 地理位置.
        /// </summary>
        internal static string GEOLOCATION {
            get {
                return ResourceManager.GetString("GEOLOCATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 表格高度占比.
        /// </summary>
        internal static string GRID_SIZE_RATIO {
            get {
                return ResourceManager.GetString("GRID_SIZE_RATIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 不再提示添加防火墙规则.
        /// </summary>
        internal static string HIDE_ADD_FIREWALL_PROMPT {
            get {
                return ResourceManager.GetString("HIDE_ADD_FIREWALL_PROMPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 隐藏地图上的窗口信息.
        /// </summary>
        internal static string HIDE_MAP_POPUP {
            get {
                return ResourceManager.GetString("HIDE_MAP_POPUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to github主页.
        /// </summary>
        internal static string HOMEPAGE {
            get {
                return ResourceManager.GetString("HOMEPAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #.
        /// </summary>
        internal static string HOP {
            get {
                return ResourceManager.GetString("HOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 主机名.
        /// </summary>
        internal static string HOSTNAME {
            get {
                return ResourceManager.GetString("HOSTNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 添加 ICMP 防火墙规则成功.
        /// </summary>
        internal static string ICMP_RULE_ADD_SUCCESS {
            get {
                return ResourceManager.GetString("ICMP_RULE_ADD_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP地理位置数据源.
        /// </summary>
        internal static string IP_GEO_DATA_PROVIDER {
            get {
                return ResourceManager.GetString("IP_GEO_DATA_PROVIDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 当前延迟.
        /// </summary>
        internal static string LAST {
            get {
                return ResourceManager.GetString("LAST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 链路本地地址.
        /// </summary>
        internal static string LINKLOCAL_ADDR {
            get {
                return ResourceManager.GetString("LINKLOCAL_ADDR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 本地回环地址.
        /// </summary>
        internal static string LOOPBACK_ADDR {
            get {
                return ResourceManager.GetString("LOOPBACK_ADDR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 丢包率(%).
        /// </summary>
        internal static string LOSS {
            get {
                return ResourceManager.GetString("LOSS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 地图数据源.
        /// </summary>
        internal static string MAP_PROVIDER {
            get {
                return ResourceManager.GetString("MAP_PROVIDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 高德地图.
        /// </summary>
        internal static string MAP_PROVIDER_AMAP {
            get {
                return ResourceManager.GetString("MAP_PROVIDER_AMAP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 百度地图.
        /// </summary>
        internal static string MAP_PROVIDER_BAIDU {
            get {
                return ResourceManager.GetString("MAP_PROVIDER_BAIDU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 最大跃点.
        /// </summary>
        internal static string MAX_HOPS {
            get {
                return ResourceManager.GetString("MAX_HOPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 菜单.
        /// </summary>
        internal static string MENU {
            get {
                return ResourceManager.GetString("MENU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MTR 模式.
        /// </summary>
        internal static string MTR_MODE {
            get {
                return ResourceManager.GetString("MTR_MODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 找不到主机 {0}。请检查该名称，然后重试。.
        /// </summary>
        internal static string NAME_NOT_RESOLVED {
            get {
                return ResourceManager.GetString("NAME_NOT_RESOLVED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 组织.
        /// </summary>
        internal static string ORGANIZATION {
            get {
                return ResourceManager.GetString("ORGANIZATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 分组请求间隔.
        /// </summary>
        internal static string PACKET_GROUP_INTERVAL {
            get {
                return ResourceManager.GetString("PACKET_GROUP_INTERVAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请求间隔.
        /// </summary>
        internal static string PACKET_INTERVAL {
            get {
                return ResourceManager.GetString("PACKET_INTERVAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 并行请求数.
        /// </summary>
        internal static string PARALLEL_REQ {
            get {
                return ResourceManager.GetString("PARALLEL_REQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设置.
        /// </summary>
        internal static string PREFERENCES {
            get {
                return ResourceManager.GetString("PREFERENCES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 私有地址（局域网）.
        /// </summary>
        internal static string PRIVATE_ADDR {
            get {
                return ResourceManager.GetString("PRIVATE_ADDR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Traceroute使用的协议.
        /// </summary>
        internal static string PROTOCOL_FOR_TRACEROUTING {
            get {
                return ResourceManager.GetString("PROTOCOL_FOR_TRACEROUTING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 每跃点探测次数.
        /// </summary>
        internal static string QUERIES_SETTING {
            get {
                return ResourceManager.GetString("QUERIES_SETTING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 退出.
        /// </summary>
        internal static string QUIT {
            get {
                return ResourceManager.GetString("QUIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 反向 DNS 查询模式.
        /// </summary>
        internal static string RDNS_MODE {
            get {
                return ResourceManager.GetString("RDNS_MODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 尝试获取完整 rDNS.
        /// </summary>
        internal static string RDNS_MODE_ALWAYS {
            get {
                return ResourceManager.GetString("RDNS_MODE_ALWAYS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 快速 rDNS（默认）.
        /// </summary>
        internal static string RDNS_MODE_DEFAULT {
            get {
                return ResourceManager.GetString("RDNS_MODE_DEFAULT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 禁用 rDNS 查询.
        /// </summary>
        internal static string RDNS_MODE_DISABLE {
            get {
                return ResourceManager.GetString("RDNS_MODE_DISABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 接收数.
        /// </summary>
        internal static string RECV {
            get {
                return ResourceManager.GetString("RECV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 红色阈值.
        /// </summary>
        internal static string RED_SPEED {
            get {
                return ResourceManager.GetString("RED_SPEED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 部分设置需重启应用才能生效.
        /// </summary>
        internal static string RESTART_TO_APPLY {
            get {
                return ResourceManager.GetString("RESTART_TO_APPLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 保存.
        /// </summary>
        internal static string SAVE {
            get {
                return ResourceManager.GetString("SAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 选择一个IP.
        /// </summary>
        internal static string SELECT_IP_DROPDOWN {
            get {
                return ResourceManager.GetString("SELECT_IP_DROPDOWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请从下拉栏中选择一个IP.
        /// </summary>
        internal static string SELECT_IP_MSGBOX {
            get {
                return ResourceManager.GetString("SELECT_IP_MSGBOX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 已发送.
        /// </summary>
        internal static string SENT {
            get {
                return ResourceManager.GetString("SENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 共享地址.
        /// </summary>
        internal static string SHARED_ADDR {
            get {
                return ResourceManager.GetString("SHARED_ADDR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 源地址.
        /// </summary>
        internal static string SRC_ADDR_SETTING {
            get {
                return ResourceManager.GetString("SRC_ADDR_SETTING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 源接口.
        /// </summary>
        internal static string SRC_INTERFACE_SETTING {
            get {
                return ResourceManager.GetString("SRC_INTERFACE_SETTING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 开始.
        /// </summary>
        internal static string START {
            get {
                return ResourceManager.GetString("START", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 标准差.
        /// </summary>
        internal static string STDEV {
            get {
                return ResourceManager.GetString("STDEV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 停止.
        /// </summary>
        internal static string STOP {
            get {
                return ResourceManager.GetString("STOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 系统 DNS.
        /// </summary>
        internal static string SYSTEM_DNS_RESOLVER {
            get {
                return ResourceManager.GetString("SYSTEM_DNS_RESOLVER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 时间(ms).
        /// </summary>
        internal static string TIME_MS {
            get {
                return ResourceManager.GetString("TIME_MS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 保留延迟显示到整数位.
        /// </summary>
        internal static string TIME_ROUNDING {
            get {
                return ResourceManager.GetString("TIME_ROUNDING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 提示.
        /// </summary>
        internal static string TIP {
            get {
                return ResourceManager.GetString("TIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 路由跟踪.
        /// </summary>
        internal static string TRACEROUTE {
            get {
                return ResourceManager.GetString("TRACEROUTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 暂不支持 TCP/UDP Traceroute.
        /// </summary>
        internal static string WINDOWS_TCP_UDP_UNSUPPORTED {
            get {
                return ResourceManager.GetString("WINDOWS_TCP_UDP_UNSUPPORTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 最大延迟.
        /// </summary>
        internal static string WORST {
            get {
                return ResourceManager.GetString("WORST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 黄色阈值.
        /// </summary>
        internal static string YELLOW_SPEED {
            get {
                return ResourceManager.GetString("YELLOW_SPEED", resourceCulture);
            }
        }
    }
}
